export enum QueryKeys {
  SETUP_APP = 'SETUP_APP',
  PRODUCT_LIST = 'PRODUCT_LIST',
  CURRENT_USER = 'CURRENT_USER',
  WISHES = 'WISHES',
  WISH_LIST = 'WISH_LIST',
  FAVORITE_COUNT = 'FAVORITE_COUNT'
}
